version: '3'
services:
  intersection_recognition_mecab:
    build:
      context: .
      dockerfile: Dockerfile-arm
    image: tiger0421/ros_intersection_recognition:latest
    container_name: ros-mecab
    network_mode: "host"
    volumes:
      - ~/share:/root/share:rw
      - ~/ros_ws/intersection_recognition:/root/catkin_ws/src/intersection_recognition:rw
    working_dir: /root
    command: /bin/bash

